### ISSUE TITLE
properly handle errors in r1cs backend

### ISSUE THREAD

**Issue by eightfilms** [zksecurity/noname#102]
#100 revealed that in [src/backends/r1cs/snarkjs.rs](https://github.com/zksecurity/noname/pull/100/files/a733b2f397ea7ee0dcc8f26638768abdf260fc40#diff-a62d19cfed9bfe61b9e9be5839be40f551f6fce4dea25c362dda1d2018e41446) that there are a few places where errors are left unhandled - these should not be silenced like in that PR, but should be properly handled.

Related comments:
https://github.com/zksecurity/noname/pull/100#discussion_r1628383632
https://github.com/zksecurity/noname/pull/100#discussion_r1628384126

**Comment by katat** [comment]
Nice spots. I think they are mostly related to file IO errors. We could create some error types in noname to wrap them up for the 3rd party library.
