### ISSUE TITLE
Support not equal operator in noname

### ISSUE THREAD

**Issue by vuvoth** [zksecurity/noname#113]
# Motivation

We should support not equal operator in noname. 

```
assert(a != b)
``` 

# Solution

**Comment by mimoo** [comment]
could be implemented as `is_zero(a - b)`, see for example https://github.com/Consensys/gnark/blob/master/frontend/cs/r1cs/api.go#L535

**Comment by mimoo** [comment]
we might already have a == b, so checking that a - b == 0 should work
