### ISSUE TITLE
add more resources to README

### ISSUE THREAD

**Issue by mimoo** [zksecurity/noname#123]
we should link to the telegram groupchat https://t.me/+VSChAOmJQgQzODcx and the zksecurity blogpost: https://www.zksecurity.xyz/blog/posts/noname-r1cs/ in the README

oh and the last stream we just did: https://www.youtube.com/live/pQer-ua73Vo?feature=share

**Comment by MuhtasimTanmoy** [comment]
Looks good? https://github.com/zksecurity/noname/pull/124
