### ISSUE TITLE
Build an online playground for noname

### ISSUE THREAD

**Issue by lognorman20** [zksecurity/noname#141]
To make the introduction of noname to new users easier as well as help developers write circuits in a simpler fashion, an online playground/compiler can be constructed. This website allows a user to write a sample noname program, compile it, and choose various options about the circuit generated such as backend system.A reference for this is Circom's [zkREPL](https://zkrepl.dev/).

**Comment by mimoo** [comment]
that would be great indeed. for reference the [go playground](https://go.dev/play/), and [rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021)

**Comment by lognorman20** [comment]
@mimoo I built a quick and dirty first version here: https://noname-code-playground.onrender.com/. 

Repo: https://github.com/lognorman20/noname-playground/tree/main

Would love for any feedback

**Comment by mimoo** [comment]
First of all, I love love love it! This is amazing. I'm going to give a demo of noname next week and will use this! Is it possible to easy load any of the examples we have in the examples folder :D?

Second: I'm trying to imagine a UI where we could easily see what constraints and witness gets produced when we create proofs. I think the best thing we can do right now is refactor noname to produce a JSON with the debug output, which could be displayed in HTML (instead of as a terminal output in the bottom). Think similar to https://godbolt.org

Third, feature request for noname itself: if we could compile noname in WASM we would not need a backend which could be quite nice. But kimchi doesn't support WASM for now so it wouldn't be that simple I believe... (cc @bkase, one )

**Comment by mimoo** [comment]
BTW the example compilation is incorrect o.o but I can't reproduce this locally. Perhaps it's because it's on a version that was buggy. A cool thing would be to display the version of noname as well :D (unfortunately we haven't been good at releasing versions consistently)

**Comment by lognorman20** [comment]
I'll work on 1) and 3). As for the compilation being incorrect, what is the expected output? The version of noname is 
`noname 0.7.0`. I installed it using `cargo install --git https://www.github.com/zksecurity/noname`

**Comment by lognorman20** [comment]
I've added predefined examples and prove button that integrates w/ snarkjs. The save proof button doesn't work yet but ill probably do it soon
![telegram-cloud-photo-size-1-5017169182604767221-y](https://github.com/user-attachments/assets/596dbff4-357e-48ce-9d82-ee032db3fbd0)
![telegram-cloud-photo-size-1-5017169182604767222-y](https://github.com/user-attachments/assets/f096fce1-5082-4572-b934-8cee90151115)

**Comment by lognorman20** [comment]
@mimoo updated with ability to prove, view snarkjs output, download all relevant proof files, and load examples

**Comment by mimoo** [comment]
> As for the compilation being incorrect, what is the expected output? 

you can see for example the kimchi assembly for the main arithmetic.no example here: https://github.com/zksecurity/noname/blob/main/examples/fixture/asm/kimchi/arithmetic.asm

for some reason your playground is showing a different assembly, and the debugging output is going crazy by adding a bunch of unrelated constraints on the last `return` statement. I can't think of a reason this would happen o_O

![Screenshot 2024-08-07 at 10 55 10 PM](https://github.com/user-attachments/assets/5e367231-8c0e-4e82-8c6a-a42170c2ee70)

**Comment by mimoo** [comment]
This is great! 

I think the `public_output` example is not the same one as the one in `example/`. Also was it a pain to set the private/public inputs for each example? Maybe we should have these set in files also so it's easy to run them manually.

**Comment by mimoo** [comment]
BTW feel free to add a link to your repo on the README here

**Comment by lognorman20** [comment]
Awesome! It was mostly just copy paste work to get the examples set up. Which `public_output` are you referring to? The one [here](https://github.com/zksecurity/noname/blob/main/examples/public_output.no) looks to be the same. For the private/public inputs I'm referring to the [test file](https://github.com/zksecurity/noname/blob/c8731484b09afd429a53b7e25fdc0d89ae92545d/src/tests/examples.rs#L175).

Side note: I've acquired the domain [noname-playground.xyz](noname-playground.xyz) for the playground. I also will be doing some backend migration in the coming days to make the system more robust, but from my experimentation, everything is working as expected. Please let me know if there's any improvements/feedback you'd like to add and I'll be happy to work on this further.
