### ISSUE TITLE
Examples section is missing

### ISSUE THREAD

**Issue by microbecode** [zksecurity/noname#162]
The root documentation states "See the [examples](https://github.com/zksecurity/noname#examples) section to see how to use it" as its last sentence. However, such section doesn't exist.

There is folder "examples", but it has no readme.

**Comment by mimoo** [comment]
ah right, I guess we could redirect to the examples/ folder and add a README there :D PRs welcome

**Comment by ewynx** [comment]
I took a stab at this since I was running the examples myself. Lmk if this is what you're looking for!
