### ISSUE TITLE
Add support for variable declaration without assignment

### ISSUE THREAD

**Issue by gio54321** [zksecurity/noname#170]
I think it would be nice to be able to implement a `zip` function like this
```rust
fn zip(a1: [Field; 3], a2: [Field; 3]) -> [[Field; 2]; 3] {
    let mut result: [[Field; 2]; 3];
    for index in 0..3 {
        result[index] = [a1[index], a2[index]];
    }
    return result;
}
```

In general it could be useful to allow the construction of arrays or structs incrementally, especially considering the introduction of generic-sized arrays.

The following code works, although it is a hack and does not scale to arbitrary array lengths
```rust
fn zip(a1: [Field; 3], a2: [Field; 3]) -> [[Field; 2]; 3] {
    let mut result = [[a1[0], a1[0]], [a1[0], a1[0]], [a1[0], a1[0]]];
    for index in 0..3 {
        result[index] = [a1[index], a2[index]];
    }
    return result;
}
```

Declaring the array uninitialized and letting the code afterwards dealing with assignment could be one of the options. This requires new syntax, and some extra checks, e.g., making sure that a warning/error is thrown when part of the array/struct does not get assigned.

**Comment by katat** [comment]
With upcoming PR https://github.com/zksecurity/noname/pull/147, it should support defining array with variable size:

```rust
let mut result = [[0; 2]; 3];
```

So this makes the language useful for practical cases where the array lengths are arbitrary. Is this already covering what you are suggesting here? Or maybe you meant something else :D

**Comment by gio54321** [comment]
Yes, indeed I meant exactly that! Sorry didn't realize this feature is already being developed in #147  :)
Closing this issue
