### ISSUE TITLE
Fix for loop range in hint function

### ISSUE THREAD

**Issue by katat** [zksecurity/noname#234]
The upper bound of for loops in hint functions is `u32`. We should disable this limit for the hint functions, since hints should be free to do any calculations.

The potential solution is to change the for loop range below to be based on `bigint` type instead of `u32`:
https://github.com/zksecurity/noname/blob/f2c0e3a3a666a2eca06f6e930bc56f30aca4f27f/src/circuit_writer/ir.rs#L402-L444

**Comment by mimoo** [comment]
I don't think it makes sense to have a loop of more than 2^32 iteration, it's just too expensive computationally, so I think it's a fine limit for now :o

**Comment by katat** [comment]
right, closing this for now
