### ISSUE TITLE
better error when a keyword is used as identifier

### ISSUE THREAD

**Issue by mimoo** [zksecurity/noname#236]
imagine that we try to create a struct with a field called `pub`:

```rust
struct Thing {
  pub: Field
}
```

this won't work as `pub` is a reserved keyword:

```
Error:   × Looks like something went wrong in parser
   ╭─[tmp/src/main.no:3:1]
 3 │ struct Thing {
 4 │   pub: Field
   ·   ─┬─
   ·    ╰── here
 5 │ }
   ╰────
  help: invalid token, expected: a lowercase alphanumeric (including
        underscore) string starting with a letter
```

The problem here is that the error doesn't help us understand why `pub` doesn't work. It would be good to write what we got instead.

Perhaps this can be done everywhere by also including the obtained token in the error? So something like this:

```rust
_ => Err(ctx.error(
                ErrorKind::ExpectedToken(TokenKind::Identifier("".to_string())),
                token.span,
            )),
```

could become

```rust
_ => Err(ctx.error(
                ErrorKind::ExpectedToken(TokenKind::Identifier("".to_string()), TokenKind::Keyword(...)),
                token.span,
            )),
```

for example

**Comment by Lynette7** [comment]
Hello, I would love to contribute to this issue.

**Comment by zedar** [comment]
Hello, please find my PR for this issue. @Lynette7 maybe you can base on my PR.

**Comment by rahul-kothari** [comment]
should this be closed now?
