### ISSUE TITLE
Replace all panics with cleaner error

### ISSUE THREAD

**Issue by mimoo** [zksecurity/noname#26]
We should replace all panics with an `ErrorKind::UnexpectedError(&'static str)` or something like that. So that a user can paste the error in the issues here if they run into one!

This error could print a message like:

> You've reached an unknown error, please copy/paste the rest of this error on https://github.com/zksecurity/noname/issues/new?title=unknown%20error
> [the string]

see https://github.com/zksecurity/noname/pull/209 for further guidance on how to convert panics to errors

in general we should not replace panics with specific errors as we don't know if we'll ever reach them. Specific errors are good if we know the user can reach them by writing bad code. 

In general the flow should be this:

* any panic in code should return an UnexpectedError to the user
* if the user reports such an error, we know that we either have a bug (we assumed that this code should never be reached, but it was reached) or we have an opportunity to write a better error for that specific error

**Comment by mahmudsudo** [comment]
can i take on this ?

**Comment by mimoo** [comment]
maybe start with just a few to show us your way of doing it :o and what it looks like from a user perspective. Also, if the error can give a link to the user to post an issue it'd be great!
