### ISSUE TITLE
noname cli: read input/output JSON from file 

### ISSUE THREAD

**Issue by vuvoth** [zksecurity/noname#92]
# Motivation 
We only read public input/output by passed in the cli as a string. This is good if we can read input from file. 

```bash
 cargo run test --backend r1cs-bn254 --path examples/arithmetic.no --private-inputs '{"private_input": "1"}' --public-inputs '{"public_input": "1"}' --debug
```
We can make cli above more simple: 

```bash
 cargo run test --backend r1cs-bn254 --path examples/arithmetic.no --private-inputs private_input.json --public-inputs ./public_inputs.json--debug 
```

# How to solve it?  
- Add option to read json file from cli.
- Rename --private-inputs, --public-inputs to --private-inputs-str... 

Another solution is try parse json, if can not we will try parse as file path.

**Comment by varun-doshi** [comment]
I'd like to work on this
